### ISSUE TITLE
Not even installing throwing NOT FOUND ERROR (E404).

### ISSUE THREAD

**Issue by AnshuMishra-kiwi** [josephchang/react-currency-flags#1]
![Screen Shot 2019-08-01 at 4 06 41 PM](https://user-images.githubusercontent.com/17636943/62287001-8dd1fa80-b476-11e9-8901-dd36f328d648.png)

**Comment by josephchang** [comment]
Hi @AnshuMishra-kiwi, it's `react-currency-flags` with an `s` at the end.

**Comment by AnshuMishra-kiwi** [comment]
> Hi @AnshuMishra-kiwi, it's `react-currency-flags` with an `s` at the end.

Got it, then you must update the README.md file, i copied the command from there.
Thanks for reply (y).

![Screen Shot 2019-08-14 at 4 32 04 PM](https://user-images.githubusercontent.com/17636943/63016409-3d648f00-beb1-11e9-86ed-c1d07c19066b.png)

**Comment by josephchang** [comment]
Ah, thanks for telling me!
